### ISSUE TITLE
Bzlmod Support

### ISSUE THREAD

**Issue by bivens-dev** [GoogleCloudPlatform/proto-gen-md-diagrams#1]
Wondering if there were any plans to also support Bzlmod workflows for this project?

**Comment by rrmcguinness** [comment]
Yeah, I think I can add that either tonight or in the AM. Thanks for the suggestion!

**Comment by rrmcguinness** [comment]
I've went ahead and just converted the entire project to a Bazel module. I can't see any real reason to support multiple configuration files and versioning. That being said, the Gazelle module is still in early beta and I'm not crazy about how Go dependencies are read. There's a hard dependency on Gazelle that requires the "go" library to be named: "io_bazel_rules_go" which breaks when you switch to @@rules_go.  Hopefully this concrete implementation will help you, finding working examples (as you've most likely found) is pretty painful.

**Comment by bivens-dev** [comment]
Thank you so much for this and the detailed comment. Much appreciated

**Comment by rrmcguinness** [comment]
Both workflows work side-by-side now and contain an end-to-end example of using the module or the workflow.

**Comment by rrmcguinness** [comment]
@bivens-dev you're welcome, thank you for the engagement.
