### ISSUE TITLE
`-o` option is ignored

### ISSUE THREAD

**Issue by raphaelboudreault** [GoogleCloudPlatform/proto-gen-md-diagrams#2]
First of all, thanks a lot for this repo, that is exactly what we needed!

At the moment, it seems like the option `-o`, which should specify an output folder, is currently ignored by the script.

**Comment by rrmcguinness** [comment]
Thank you for that, I'll verify and patch. I've been using it with Bazel and Hugo specifically which handles output differently.

**Comment by AugustBender** [comment]
Hey there, any update on this?

**Comment by rrmcguinness** [comment]
Hey August, thanks for reaching out. I'm currently working on a heads down
sprint until mid January. I will take care of this then. My sincere apology
for the delay.
