### ISSUE TITLE
comments are always wrapped in html

### ISSUE THREAD

**Issue by chicco785** [GoogleCloudPlatform/proto-gen-md-diagrams#5]
Due to that we have to use html syntax in the comments to use code blocks and link formatting, for example, rather than markdown syntax (which is a bit a counter sense given that we are generating markdown documentation, and that go documentation supports markdown syntax as far as i understand)

**Comment by rrmcguinness** [comment]
Greetings, this utility is specifically used with Hugo to generate document sites. It's actually the reason I wrote the utility. What is that you're proposing?

**Comment by chicco785** [comment]
greetings to you @rrmcguinness :) sorry for being slow, I was out of office.

Hugo may be interesting also for us in the future. May be I can ad flag to serialise comments without HTML, so that default behaviour won't change.

What do you think?

**Comment by rrmcguinness** [comment]
That sounds like a good approach. Would you like to add that patch or is
that something you'd like me to put in the backlog. Either works for me.

**Comment by chicco785** [comment]
happy to give it a try under your guidance :)

**Comment by chicco785** [comment]
we filled in the CLA form, hopefully every thing  will work smoothly. tomorrow i will spend some time looking at the code, if it's a quick thing, I will submit a PR before the end of the week ;)
